'use strict';
const bcrypt = require('bcrypt');

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    Example: await queryInterface.bulkInsert(
      "Users",
      [
        {
          username: "Александр",
          email: "aleksandr@mail.ru",
          password: await bcrypt.hash("12345", 10),
          score: 100,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Андрей",
          email: "andrej@rumbler.ru",
          password: await bcrypt.hash("12345", 10),
          score: 100,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Антон",
          email: "anton@rumbler.ru",
          password: await bcrypt.hash("12345", 10),
          score: 100,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Артем",
          email: "artem@rumbler.ru",
          password: await bcrypt.hash("12345", 10),
          score: 100,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Артур",
          email: "artur@rumbler.ru",
          password: await bcrypt.hash("12345", 10),
          score: 100,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Борис",
          email: "boris@rumbler.ru",
          password: await bcrypt.hash("12345", 10),
          score: 100,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Вадим",
          email: "vadim@rumbler.ru",
          password: await bcrypt.hash("12345", 10),
          score: 150,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Валерий",
          email: "valerij@rumbler.ru",
          password: await bcrypt.hash("12345", 10),
          score: 100,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Владимир",
          email: "vladimir@rumbler.ru",
          password: await bcrypt.hash("12345", 10),
          score: 130,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Виталий",
          email: "vitalij@rumbler.ru",
          password: await bcrypt.hash("12345", 10),
          score: 150,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Вячеслав",
          email: "vyacheslav@rumbler.ru",
          password: await bcrypt.hash("12345", 10),
          score: 5000,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Геннадий",
          email: "gennadij@rumbler.ru",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Георгий",
          email: "georgij@rumbler.ru",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Дмитрий",
          email: "dmitrij@rumbler.ru",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Евгений",
          email: "evgenij@rumbler.ru",
          password: await bcrypt.hash("12345", 10),
          score: 2200,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Иван",
          email: "ivan@rumbler.ru",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Игорь",
          email: "igor@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Илья",
          email: "ilya@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Кирилл",
          email: "kirill@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Константин",
          email: "konstantin@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Михаил",
          email: "mihail@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Никита",
          email: "nikita@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Николай",
          email: "nikolaj@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Олег",
          email: "oleg@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Павел",
          email: "pavel@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Анастасия",
          email: "roman@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 1700,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Сергей",
          email: "sergej@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Степан",
          email: "stepan@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Юрий",
          email: "yurij@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Даниил",
          email: "daniil@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Денис",
          email: "denis@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Егор",
          email: "egor@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Захар",
          email: "zahar@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Максим",
          email: "maksim@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Марк",
          email: "mark@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Анастасия",
          email: "anastasiya@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Анна",
          email: "anna@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Валентина",
          email: "valentina@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Варвара",
          email: "varvara@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Вера",
          email: "vera@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Виктория",
          email: "viktoriya@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Дарья",
          email: "darya@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Екатерина",
          email: "ekaterina@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Елена",
          email: "elena@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Елизавета",
          email: "Elizaveta@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Ксения",
          email: "kseniya@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Мария",
          email: "mariya@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Маргарита",
          email: "margarita@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Наталья",
          email: "natalya@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Ольга",
          email: "olga@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Татьяна",
          email: "tatyana@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Юлия",
          email: "yuliya@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Алина",
          email: "alina@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Валерия",
          email: "valeriya@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Вероника",
          email: "veronika@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Ирина",
          email: "irina@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Карина",
          email: "karina@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Лилия",
          email: "liliya@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Светлана",
          email: "svetlana@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "София",
          email: "sofiya@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Яна",
          email: "yana@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Александра",
          email: "aleksandra@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Ульяна",
          email: "ulyana@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Мирослава",
          email: "miroslava@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: "Агата",
          email: "agata@gmail.com",
          password: await bcrypt.hash("12345", 10),
          score: 0,
          isCompany: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface) {
    Example: await queryInterface.bulkDelete('Users', null, {});
  },
};
